services:
  db_service:
    image: postgres:16
    container_name: db
    env_file:
      - .env
    environment:
      POSTGRES_USER: Dan4i4ek31
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fast_api
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data: